### ISSUE TITLE
Trying to get the runemetrics profile of a F2P Player marks it as a non-private-profile

### ISSUE THREAD

**Issue by johnvictorfs** [johnvictorfs/rs3clans.py#18]
The call to a F2P Player's Profile with the runemetrics api returns:
```json
{
"error": "NOT_A_MEMBER",
"loggedIn": "false"
}
```

The error `NOT_A_MEMBER` should be accounted for, possibly by considering the profile private?

Change at: https://github.com/johnvictorfs/rs3clans.py/blob/master/rs3clans/players.py#L262-L271

**Comment by Guilherme-Vasconcelos** [comment]
Not possible to reproduce issue.

![image](https://user-images.githubusercontent.com/49197151/67779919-20694200-fa44-11e9-842f-6b15c5177bd7.png)
![image](https://user-images.githubusercontent.com/49197151/67779937-25c68c80-fa44-11e9-9f5c-f40be11e0027.png)
